[package]
name = "kairo-assets"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Project-scoped texture assets for Kairo2D"

[dependencies]
fontdue.workspace = true
serde.workspace = true
serde_json.workspace = true
kairo-core.workspace = true
anyhow.workspace = true
image.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
