[actions.activate]
keyboard = ["space"]
mouse = [1]
gamepad = ["a"]

[axes.move_x]
negative = ["a", "left"]
positive = ["d", "right"]
gamepad_axis = "left_x"
dead_zone = 0.18

[axes.move_y]
negative = ["w", "up"]
positive = ["s", "down"]
gamepad_axis = "left_y"
dead_zone = 0.18

[actions.accept]
keyboard=["enter", "space"]
gamepad=["a"]
[actions.pause]
keyboard=["escape"]
gamepad=["start"]
[actions.mark]
keyboard=["b"]
gamepad=["y"]
